version: "3.8"

services:
  web:
    build: .
    container_name: php-web
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - images-data:/usr/share/nginx/html/images
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: web-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: website
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password  # Fix lỗi xác thực khi kết nối

  image-server:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    container_name: my-nginx
    restart: always
    volumes:
      - images:/usr/share/nginx/html/images
    ports:
      - "8081:80"


  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: web-phpmyadmin
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
      PMA_ARBITRARY: 1  # Cho phép nhập host tùy ý
    ports:
      - "8082:80"

volumes:
  db_data:
  images-data:
