version: "3.8"

services:
  web:
    build: .
    container_name: php-app
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./images:/usr/share/nginx/html/images
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: website
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
      - ./php:/var/www/html
    ports:
      - "3306:3306"

  image-server:
    image: nginx:latest
    container_name: image-server
    volumes:
      - ./images:/usr/share/nginx/html/images  # Mount thư mục chứa ảnh
    ports:
      - "8081:80"  # Chạy Nginx trên cổng 8081 để truy cập ảnh

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin-container
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8082:80"
volumes:
  db_data:
  