FROM nginx:latest

# Tạo thư mục chứa ảnh (nếu chưa tồn tại)
RUN mkdir -p /usr/share/nginx/html/images/product

# Cấp quyền nhưng không dùng 777
RUN chmod -R 775 /usr/share/nginx/html/images && \
    chown -R nginx:nginx /usr/share/nginx/html/images

# Copy ảnh vào container (nếu có sẵn)
COPY images/ /usr/share/nginx/html/images/

# Copy file cấu hình Nginx
COPY nginx.conf /etc/nginx/nginx.conf

# Chạy Nginx ở foreground
CMD ["nginx", "-g", "daemon off;"]
