version: "3.8"

services:
  web:
    build: .
    container_name: php-web
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./images:/usr/share/nginx/html/images
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: web-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: website
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
      - ./php:/var/www/html
    ports:
      - "3306:3306"

  image-server:
    build:
      context: .
      dockerfile: Dockerfile-nginx  # Sử dụng Dockerfile riêng cho Nginx
    container_name: my-nginx
    volumes:
      - ./images:/usr/share/nginx/html/images  # Gắn thư mục ảnh vào Nginx
    ports:
      - "8081:80"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: web-phpmyadmin
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8082:80"
volumes:
  db_data:
  