# Sử dụng Nginx làm server
FROM nginx:latest

# Copy thư mục chứa hình ảnh vào thư mục mặc định của Nginx
COPY ./images /usr/share/nginx/html/images
#COPY nginx/nginx.conf /etc/nginx/nginx.conf

# Expose cổng 80
EXPOSE 80